### ISSUE TITLE
WARN and FORBIDWARN

### ISSUE THREAD

**Issue by shantanuo** [fin-w/LibreOffice-Geiriadur-Cymraeg-Welsh-Dictionary#2]
I can see that these 2 lines are used in the affix file.

WARN !
FORBIDWARN

And used in the corpus like this...

adlamu/H
adlamych/H!

But it is also possible to use this option...

FORBIDDENWORD !

Is it any different than the WARN parameter?

**Comment by fin-w** [comment]
Hello! Thank you for your comment. It seems you are right, I just tested the difference between 
```
WARN !
FORBIDWARN
```
and 
```
FORBIDDENWORD !
```
and both options output the same word lists. They seem to be equivalent and both correctly specify the words to mark as incorrect.
