### ISSUE TITLE
Numbers in hyphenation rules

### ISSUE THREAD

**Issue by shantanuo** [fin-w/LibreOffice-Geiriadur-Cymraeg-Welsh-Dictionary#3]
This is not directly related to your repo, but asking for help.

English Hyphenation file looks something like this...
```
LEFTHYPHENMIN 2
RIGHTHYPHENMIN 3
COMPOUNDLEFTHYPHENMIN 2
COMPOUNDRIGHTHYPHENMIN 3
.a2ch4
.ad1d4
.am5at
```
1, 2, 4 and 5 numbers are added next to characters. Does it mean it is OK to hyphenate next to "a" but not OK to hyphenate next to "ad"?

**Comment by fin-w** [comment]
I've never used hyphenation rules before so I don't know, sorry.
